board/board/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("post_board.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("allauth.urls")),

]

board/board/post_board/urls.py
from django.urls import path, include
from .views import (index,
                    BoardList,
                    BoardCreate,
                    BoardDetail,
                    BoardCreate,
                    BoardEdit,
                    BoardDelete,
                    approved_comment,
                    decline_comment,
                    wait_comment)


app_name = 'post_board'  # имя приложения, это учитывается в шаблонах и во views
urlpatterns = [
    path('main/', BoardList.as_view(), name='index'),

    path('board_create/', BoardCreate.as_view(), name='board_create'),
    path('board_detail/<int:pk>/', BoardDetail, name='board_detail'),
    path('board_edit/<int:pk>/', BoardEdit.as_view(), name='board_edit'),
    path('board_delete/<int:pk>/', BoardDelete.as_view(), name='board_delete'),
    
    path('wait_comment/<int:pk>/', wait_comment, name='wait'),
    path('decline_comment/<int:pk>/', decline_comment, name='decline'),
    path('approved_comment/<int:pk>/', approved_comment, name='approved'),
]

board/board/templates/board/board_create.html
{% extends 'base/base.html' %}
{% block title %}Post Edit Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-primary btn-sm" type="submit" value="Save">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board/board/templates/board/board_delete.html
{% extends 'base/base.html' %}
{% block title %}Post Detail Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <div class="alert alert-danger">
                        Хотите удалить объявление?
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        <a class="btn btn-secondary btn-sm"
                            href="{% url 'post_board:board_detail' post.id %}">Cancel</a>
                        <input class="btn btn-primary btn-sm" type="submit" value="Confirm">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board/board/templates/board/board_detail.html
{% extends 'base/base.html' %}
{% block title %}Post Detail Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
	<div class="row mt-5 pt-3">
		<div class="col-md-8 offset-md-2">
			<div class="card my-3 shadow">
				<div class="card-body">
					<div class="row">

						<div class="col-md-8">
							<small>{{ post.dateCreation }}</small>
							<p>{{post.categoryType}} </p>

							<span><a class="btn btn-danger float-right btn-sm"
									href="{% url 'post_board:board_delete' post.id %}">Удалить</a></span>
							<span><a class="btn btn-primary mx-2 float-right btn-sm"
									href="{% url 'post_board:board_edit' post.id %}">Редактировать</a></span>

							<hr>
							<h4>{{ post.postTitle }}</h4>
							<p>
								{{ post.content }}
							</p>
						</div>
					</div>
					<p class="mt-3">
						<a class="" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false"
							aria-controls="collapseExample">
							Comments: {{ post.comment_count }}
						</a>
					</p>
					<div class="collapse" id="collapseExample">
						<div style="height: 250px; overflow-y: scroll;" class="card card-body">
							{% for comment in post.comments %}
							<p class="text-justify">
							<div class="row">
								<div class="col-md-3">
									{{ comment.commentUser.username }}
								</div>
								<div class="col-md-6">
									{{ comment.commentText }}
								</div>
								<div class="col-md-3">
									{{ comment.status }}
								</div>
							</div>
							<hr>
							</p>
							{% endfor %}
						</div>
					</div>
					<form method="POST">
						{% csrf_token %}
						{{ c_form|crispy }}
						<input class="btn btn-primary btn-sm" type="submit" value="Comment">
					</form>
				</div>
			</div>
		</div>
	</div>

</div>
{% endblock %}

board/board/templates/board/board_edit.html
{% extends 'base/base.html' %}
{% block title %}Board Edit Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-primary btn-sm" type="submit" value="Save">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board/board/templates/board/index.html
{% extends 'base/base.html' %}
{% block title %}Home Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-3">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-danger float-left btn-lm"
                            formaction="{% url 'post_board:board_create' %}">Подать объявление</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            {% for post in Posts %}
            <div class="card shadow my-3">
                <div class="card-body">
                    <div class="row">

                        <div class="col-md-8">
                            <small>{{post.postTitle}} : {{post.dateCreation|date:'d M Y'}}</small>
                            <hr>
                            <a class="h3" href="{{post.get_absolute_url}}">{{post.postText}} </a>
                            <p class="text-justify my-3">
                            <p>{{post.categoryType}} </p>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}