board/board/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("post_board.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("allauth.urls")),

]

board/board/post_board/urls.py
from django.urls import path, include
from .views import (index,
                    BoardList,
                    BoardCreate,
                    BoardDetail,
                    BoardCreate,
                    BoardEdit,
                    BoardDelete,
                    approved_comment,
                    decline_comment,
                    wait_comment)


app_name = 'post_board'  # имя приложения, это учитывается в шаблонах и во views
urlpatterns = [
    path('main/', BoardList.as_view(), name='index'),

    path('board_create/', BoardCreate.as_view(), name='board_create'),
    path('board_detail/<int:pk>/', BoardDetail, name='board_detail'),
    path('board_edit/<int:pk>/', BoardEdit.as_view(), name='board_edit'),
    path('board_delete/<int:pk>/', BoardDelete.as_view(), name='board_delete'),
    
    path('wait_comment/<int:pk>/', wait_comment, name='wait'),
    path('decline_comment/<int:pk>/', decline_comment, name='decline'),
    path('approved_comment/<int:pk>/', approved_comment, name='approved'),
]

board/board/users/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_view


app_name = 'users'
urlpatterns = [
    path('sign_up/', views.sign_up, name='users-sign-up'),
    path('profile/', views.profile, name='users-profile'),
    path('', auth_view.LoginView.as_view(template_name='users/login.html'),
         name='users-login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'),
         name='users-logout'),
    path('password_reset/', auth_view.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset_done/', auth_view.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         views.activate, name='activate'),

]

board/board/users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

# Create your models here.


class ProfileModel(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='profilemodel')
    image = models.ImageField(default='default.jpg', upload_to='static/uploads/', validators=[
                              FileExtensionValidator(['png', 'jpg'])])

    def __str__(self):
        return self.user.username

board/board/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import ProfileModel
from django import forms


class SignUpForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'email', 'password1', 'password2']:
            self.fields[fieldname].help_text = None


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'email']:
            self.fields[fieldname].help_text = None


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = ProfileModel
        fields = ['image']

board/board/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import SignUpForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from post_board.models import Comment, Post, Category
from django.core.mail import send_mail, EmailMessage
from .token import account_activation_token
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.views.decorators.http import require_http_methods
from django.utils.encoding import force_bytes, force_str
from django.http import HttpResponse
from django.template.loader import render_to_string
from .models import ProfileModel
import os
# Create your views here.


def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            # save form in the memory not in database
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            # to get the domain of the current site
            current_site = get_current_site(request)
            mail_subject = 'Activation link has been sent to your email id'
            message = render_to_string('users/acc_activate_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignUpForm()
    context = {
        'form': form,
    }
    return render(request, 'users/sign_up.html', context)


@login_required
def profile(request):
    # определяем формы контекста
    if request.method == 'GET':
        posts = Post.objects.filter(author=request.user)
        comments = Comment.objects.all()
        user = ProfileModel.objects.get(user=request.user)
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST or None, instance=request.user)
        # p_form = ProfileUpdateForm(
        # request.POST or None, request.FILES or None, instance=request.user.profilemodel)
        if u_form.is_valid():  # and p_form.is_valid():
            u_form.save()
            # p_form.save()
            return redirect('users:users-profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        # p_form = ProfileUpdateForm(instance=request.user.profilemodel)
    # передаем контектс
    context = {
        'u_form': u_form,
        # 'p_form': p_form,
        'posts': posts,
        'comments': comments,
        'profile': user,
    }

    return render(request, 'users/profile.html', context)


def activate(request, uidb64, token):
    User = request.user()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

board/board/templates/users/acc_activate_email.html
{% autoescape off %}
Здравствуйте {{ user.username }},
Пожалуйста подтвердите вашу регистрацию,
http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}
{% endautoescape %}

board/board/templates/users/login.html
{% extends 'base/base.html' %}
{% block title %}Login Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="cover">
  <div class="container">
    <div class="row mt-5 pt-3">
      <div class="col-md-5 offset-md-6">
        <div class="card my-3 shadow">
          <div class="card-body">
            <h4>Вход в систему</h4>
            <hr>
            <form method="POST">
              {% csrf_token %}
              {{ form|crispy }}
              <input class="btn btn-primary btn-block" type="submit" value="Login">
            </form>
            <hr>
            <hr>
            <div class="text-center">
              <a class="btn btn-success" href="{% url 'users:users-sign-up' %}">Создать аккаунт</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

board/board/templates/users/logout.html
{% extends 'base/base.html' %}
{% block title %}Logout Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-6 offset-md-3">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Logout Page</h4>
                    <hr>
                    <div class="alert alert-info">
                        You have been logged out.
                    </div>
                    <a href="{% url 'users:users-login' %}">Login</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

board/board/templates/users/password_reset.html
{% extends 'base/base.html' %}
{% block title %}Password Reset Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Password Reset Page</h4>
                    <hr>
                    <div class="alert alert-info">
                        Enter email and a mail will be sent with instructions to reset password
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-primary btn-block" type="submit" value="Reset Password">
                    </form>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

board/board/templates/users/password_reset_complete.html
{% extends 'base/base.html' %}
{% block title %}Password Reset Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Password Reset Page</h4>
                    <hr>
                    <div class="alert alert-info">
                        Enter email and a mail will be sent with instructions to reset password
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-primary btn-block" type="submit" value="Reset Password">
                    </form>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

board/board/templates/users/password_reset_confirm.html
{% extends 'base/base.html' %}
{% block title %}Password Reset Confirm Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Password Reset Confirm Page</h4>
                    <hr>
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-primary btn-block" type="submit" value="Reset Password Confirm">
                    </form>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

board/board/templates/users/password_reset_done.html
{% extends 'base/base.html' %}
{% block title %}Password Reset Done Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-8 offset-md-2">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <h4>Password Reset Done Page</h4>
                    <hr>
                    <div class="alert alert-info">
                        An mail with instructions to reset password has been sent to the email you provided.
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

board/board/templates/users/profile.html
{% extends 'base/base.html' %}
{% block title %}Profile Page{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-6 offset-md-3">
            <div class="card my-3 shadow">
                <div class="card-body">
                    <span class="h4">Профиль</span>
                    <!-- Button trigger modal -->
                    <span>
                        <button type="button" class="btn btn-info float-right btn-sm" data-toggle="modal"
                            data-target="#exampleModal">
                            Редактировать профиль
                        </button>
                    </span>
                    <hr>
                    <div class="row">
                        <div class="col-md-4">
                            <img class="img-thumbnail" src="/static/{{profile.image}}" alt="profile-img">
                        </div>
                        <div class="col-md-8">
                            <h4>Имя: {{ user.username }}</h4>
                            <h4>Email: {{ user.email }} </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row mt-5 pt-3">
        <div class="col-md-6 offset-md-3">
            {% for post in posts %}
            <div class="card shadow my-3">
                <div class="card-body">
                    <div class="row">

                        <div class="col-md-8">
                            <small>{{ post.dateCreation }}</small>
                            <p>{{post.categoryType}} </p>

                            <span><a class="btn btn-danger float-right btn-sm"
                                    href="{% url 'post_board:board_delete' post.id %}">Удалить</a></span>
                            <span><a class="btn btn-primary mx-2 float-right btn-sm"
                                    href="{% url 'post_board:board_edit' post.id %}">Редактировать</a></span>
                            <hr>
                            <h4>{{ post.postTitle }}</h4>
                            <p>
                                {{ post.content }}
                            </p>
                        </div>
                    </div>
                    <p class="mt-3">
                        <a class="" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false"
                            aria-controls="collapseExample">
                            Comments: {{ post.comment_count }}
                        </a>
                    </p>
                    <div class="collapse" id="collapseExample">
                        <div style="height: 250px; overflow-y: scroll;" class="card card-body">
                            {% for comment in post.comments %}
                            <p class="text-justify">
                            <div class="row">
                                <div class="col-md-3">
                                    {{ comment.commentUser.username }}
                                </div>
                                <div class="col-md-9">
                                    {{ comment.commentText }}
                                    {{ comment.status }}
                                </div>
                                <form method="post" action="{% url 'post_board:decline' comment.pk %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger float-right btn-sm">Отклонить</button>
                                </form>
                                <form method="post" action="{% url 'post_board:approved' comment.pk %}">
                                    {% csrf_token %}
                                    <button type="submit"
                                        class="btn btn-primary mx-2 float-right btn-sm">Подтвердить</button>
                                </form>
                            </div>
                            <hr>
                            </p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Редактироваь профиль</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <img class="img-thumbnail" src="{{ user.profilemodel.image.url }}" alt="">
                    </div>
                    <div class="col-md-8">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ u_form|crispy }}
                            {{ p_form|crispy }}

                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary btn-sm"
                                    data-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-primary btn-sm">Save</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


{% endblock %}

board/board/templates/users/sign_up.html
{% extends 'base/base.html' %}
{% block title %}Sign Up{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<div class="cover">
	<div class="container ">
		<div class="row mt-5 pt-3">
			<div class="col-md-5 offset-md-6">
				<div class="card my-3 shadow">
					<div class="card-body">
						<h4>Регистрация</h4>
						<hr>
						<form method="POST">
							{% csrf_token %}
							{{ form.as_p }}
							<input class="btn btn-primary btn-block" type="submit" value="Создать">
						</form>
						<a class="btn btn-success"
							href="http://127.0.0.1:8000/accounts/yandex/login/?process=login">Yandex вход</a>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}