board/board/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("post_board.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("allauth.urls")),

]

board/board/post_board/urls.py
from django.urls import path, include
from .views import (index,
                    BoardList,
                    BoardCreate,
                    BoardDetail,
                    BoardCreate,
                    BoardEdit,
                    BoardDelete,
                    approved_comment,
                    decline_comment,
                    wait_comment)


app_name = 'post_board'  # имя приложения, это учитывается в шаблонах и во views
urlpatterns = [
    path('main/', BoardList.as_view(), name='index'),

    path('board_create/', BoardCreate.as_view(), name='board_create'),
    path('board_detail/<int:pk>/', BoardDetail, name='board_detail'),
    path('board_edit/<int:pk>/', BoardEdit.as_view(), name='board_edit'),
    path('board_delete/<int:pk>/', BoardDelete.as_view(), name='board_delete'),
    
    path('wait_comment/<int:pk>/', wait_comment, name='wait'),
    path('decline_comment/<int:pk>/', decline_comment, name='decline'),
    path('approved_comment/<int:pk>/', approved_comment, name='approved'),
]

board/board/users/urls.py
from django.urls import path
from .import views
from django.contrib.auth import views as auth_view


app_name = 'users'
urlpatterns = [
    path('sign_up/', views.sign_up, name='users-sign-up'),
    path('profile/', views.profile, name='users-profile'),
    path('', auth_view.LoginView.as_view(template_name='users/login.html'),
         name='users-login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='users/logout.html'),
         name='users-logout'),
    path('password_reset/', auth_view.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset_done/', auth_view.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
         views.activate, name='activate'),

]

board/board/templates/base/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!--Custome CSS-->
    <link rel="stylesheet" href="{% static '/style.css' %}">

    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% include 'base/nav.html' %}

    {% block content %}

    {% endblock %}

    {% block menu%}

    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
</body>

</html>

board/board/templates/base/nav.html
<nav class="navbar navbar-expand-lg navbar-primary bg-primary fixed-top">
    <div class="container">
        {% if request.user.is_authenticated %}
        <a class="navbar-brand text-white" href="{% url 'post_board:index' %}">ДОСКА ОБЪЯВЛЕНИЙ</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link text-white" href="{% url 'users:users-profile' %}">Профиль <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'users:users-logout' %}">Выход</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link text-white" href="{% url 'users:users-sign-up' %}">Регистрация <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'users:users-login' %}">Вход</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>